Repository turnitin/moodle-mod_turnitintooltwo, pull requests merged in 2024-07, with the labels that each got.

#695 Less strict checking of the expected title string in the page title
  tests/unit/classes/view/turnitintooltwo_view_test.php
Labels: investigating

#703 fixed optional parameter before required parameter issue with show_form()
  mod_form.php
Labels: duplicate

#728 Fix deprecated function usages
  lib.php
  turnitintooltwo_assignment.class.php
Labels: investigating

#707 Fix failing Behat test
  mod_form.php
Labels: investigating

#710 Fix issue #709
  turnitintooltwo_user.class.php
Labels: investigating

#233 fix missing slashes in sdk inclusion paths
  sdk/api.class.php
  sdk/assignmentsoap.class.php
  sdk/classsoap.class.php
  sdk/log.class.php
  sdk/lti.class.php
  sdk/membershipsoap.class.php
  sdk/response.class.php
  sdk/soap.class.php
  sdk/submissionsoap.class.php
  sdk/tiiassignment.class.php
  sdk/tiiclass.class.php
  sdk/tiilti.class.php
  sdk/tiisubmission.class.php
  sdk/tiiuser.class.php
  sdk/usersoap.class.php
Labels: scheduled for next release
